# Generated by Django 3.1.1 on 2023-08-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230817_1333'),
        ('main_app', '0002_auto_20230824_1813'),
    ]

    operations = [
    ]
